### ISSUE TITLE
Dm_Control Dependencies

### ISSUE THREAD

**Issue by AlexanderKhazatsky** [deepmind/dm_robotics#14]
Hello, there is currently an issue when using the IK modules with dm_control==1.0.1 (error below). This is resolved by using dm_control 1.0.5. Could you please update the dependencies?

Traceback (most recent call last):
  File "/home/sasha/anaconda3/envs/poly-backup/lib/python3.8/site-packages/zerorpc/core.py", line 153, in _async_task
    functor.pattern.process_call(self._context, bufchan, event, functor)
  File "/home/sasha/anaconda3/envs/poly-backup/lib/python3.8/site-packages/zerorpc/patterns.py", line 30, in process_call
    result = functor(*req_event.args)
  File "/home/sasha/anaconda3/envs/poly-backup/lib/python3.8/site-packages/zerorpc/decorators.py", line 44, in __call__
    return self._functor(*args, **kargs)
  File "/home/sasha/Desktop/household_robot_dataset/r2d2/franka/robot.py", line 31, in launch_robot
    self._ik_solver = RobotIKSolver()
  File "/home/sasha/Desktop/household_robot_dataset/r2d2/real_robot_ik/robot_ik_solver.py", line 13, in __init__
    self._physics = mjcf.Physics.from_mjcf_model(self._arm.mjcf_model)
  File "/home/sasha/anaconda3/envs/poly-backup/lib/python3.8/site-packages/dm_control/mjcf/physics.py", line 495, in from_mjcf_model
    return cls.from_xml_string(xml_string=xml_string, assets=assets)
  File "/home/sasha/anaconda3/envs/poly-backup/lib/python3.8/site-packages/dm_control/mujoco/engine.py", line 424, in from_xml_string
    return cls.from_model(model)
  File "/home/sasha/anaconda3/envs/poly-backup/lib/python3.8/site-packages/dm_control/mujoco/engine.py", line 407, in from_model
    return cls(data)
  File "/home/sasha/anaconda3/envs/poly-backup/lib/python3.8/site-packages/dm_control/mujoco/engine.py", line 122, in __init__
    self._reload_from_data(data)
  File "/home/sasha/anaconda3/envs/poly-backup/lib/python3.8/site-packages/dm_control/mjcf/physics.py", line 530, in _reload_from_data
    super()._reload_from_data(data)
  File "/home/sasha/anaconda3/envs/poly-backup/lib/python3.8/site-packages/dm_control/mujoco/engine.py", line 370, in _reload_from_data
    self._warnings_before = np.empty_like(self._warnings)
  File "<__array_function__ internals>", line 180, in empty_like
RuntimeError: Caught an unknown exception!

**Comment by JeanElsner** [comment]
Do you mean the QP-optimization Cartesian controller or the MoMa IK utility (based on the same controller actually)? It's difficult to tell from your stack trace what it is you're doing, but the exception is thrown during instantiation of the mjcf model, so the controller is unlikely to be the cause. By the way both modules are still running fine for me.

**Comment by shacklestone** [comment]
We now use dm_control 1.0.8
